/**
 *
 * $Id$
 */
package circuiteditor.validation;

import circuiteditor.ActionLiaison;
import circuiteditor.ElementCircuit;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link circuiteditor.ActionElementCircuit}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActionElementCircuitValidator {
	boolean validate();

	boolean validateLiaisonsModifiees(EList<ActionLiaison> value);
	boolean validateElementModifie(ElementCircuit value);
}
