/**
 *
 * $Id$
 */
package circuiteditor.validation;

import circuiteditor.ElementCircuit;
import circuiteditor.ElementType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link circuiteditor.ElementCircuit}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ElementCircuitValidator {
	boolean validate();

	boolean validateEmplacementX(int value);
	boolean validateEmplacementY(int value);
	boolean validateName(String value);
	boolean validateDescription(String value);
	boolean validateSourceMax(int value);
	boolean validateCibleMax(int value);
	boolean validateEstCircuitValide(boolean value);
	boolean validateEstModifier(boolean value);
	boolean validateType(ElementType value);
	boolean validateEntree(EList<ElementCircuit> value);
	boolean validateSortie(EList<ElementCircuit> value);
}
