/**
 *
 * $Id$
 */
package circuiteditor.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link circuiteditor.LigneTableDeVerite}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LigneTableDeVeriteValidator {
	boolean validate();

	boolean validateEntrees(EList<Boolean> value);
	boolean validateSortie(EList<Boolean> value);

	boolean validateSortie(boolean value);
}
