/**
 *
 * $Id$
 */
package circuiteditor.validation;

import circuiteditor.TypePorteStandard;

/**
 * A sample validator interface for {@link circuiteditor.PorteStandard}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PorteStandardValidator {
	boolean validate();

	boolean validateTypePorte(TypePorteStandard value);
}
