/**
 *
 * $Id$
 */
package circuiteditor.validation;

import circuiteditor.Circuit;
import circuiteditor.ElementTableVerite;
import circuiteditor.LigneTableDeVerite;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link circuiteditor.TableDeVerite}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TableDeVeriteValidator {
	boolean validate();

	boolean validateCircuit(Circuit value);
	boolean validatePossede(EList<LigneTableDeVerite> value);

	boolean validateElement(ElementTableVerite value);
}
